### ISSUE TITLE
Properties array

### ISSUE THREAD

**Issue by ghost** [benjy/REA-XML-Parser#1]
Hi Ben, sorry mate - didn't know how to use the pull request, first time on github.

The forked version seems to work properly, but I like how your fields are arranged, so will wait for the code merge.

Issue: the $properties array does not recognise ['residential'] or ['rental'] if it is the 2nd entry in the xml file. It only recognises the 1st entry. (Eg if the first xml entry is residential, all residential entries are picked up but rentals are ignored).

Cheers

Pete

**Comment by ghost** [comment]
Have you guys found on a fix for this? I have the same issue, I doubt this was always an issue. I think it has to do with updated hooks/actions.

**Comment by benjy** [comment]
I actually rewrote that function for a project so i've pushed it out. https://github.com/benjy14/REA-XML-Parser/commit/9d2341b119d519813559d97229e7837df5e9bd8a
